version: '3'
services:
  power-plants-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    env_file:
      - .env
    depends_on:
      - power-plants-db
    networks:
      - app-network

  power-plants-db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ${DATABASE_ALLOW_EMPTY_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge