version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    ports:
      - "4000:3000"
    depends_on:
      - db
      - mongodb
    env_file:
      - .env
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongodb:27017/power_plants
    networks:
      - app-network

  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app-network

  mongodb:
      image: mongo:4.4
      ports:
        - "27017:27017"
      networks:
        - app-network

networks:
  app-network:
    driver: bridge